package view;

/**
 *
 * @author rafacampa9
 */
public class Alquiler extends javax.swing.JFrame {

    /**
     * Creates new form Alquiler
     */
    public Alquiler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lNumExp = new javax.swing.JLabel();
        txtNumExp = new javax.swing.JTextField();
        lFechaEntrada = new javax.swing.JLabel();
        fechaEntrada = new com.toedter.calendar.JDateChooser();
        lFechaSalida = new javax.swing.JLabel();
        fechaSalida = new com.toedter.calendar.JDateChooser();
        lDniCliente = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        lIdVivienda = new javax.swing.JLabel();
        txtIdVivienda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbPagado = new javax.swing.JComboBox<>();
        btnInsert = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));
        jPanel1.add(jPanel3);

        lTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText("ARRENDAMIENTOS");
        jPanel1.add(lTitle);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNumExp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lNumExp.setText("Número de Expediente:");
        jPanel2.add(lNumExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 140, 30));

        txtNumExp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtNumExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 160, 30));

        lFechaEntrada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lFechaEntrada.setText("Fecha de Entrada:");
        jPanel2.add(lFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 130, 30));

        fechaEntrada.setMaxSelectableDate(new java.util.Date(1735603265000L));
        fechaEntrada.setMinSelectableDate(new java.util.Date(65000L));
        fechaEntrada.setName("fechaEntrada"); // NOI18N
        jPanel2.add(fechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 160, 30));

        lFechaSalida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lFechaSalida.setText("Fecha de Salida:");
        jPanel2.add(lFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 40));

        fechaSalida.setMaxSelectableDate(new java.util.Date(1924905678000L));
        fechaSalida.setMinSelectableDate(new java.util.Date(1672531278000L));
        fechaSalida.setName("fechaSalida"); // NOI18N
        jPanel2.add(fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 160, 30));

        lDniCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lDniCliente.setText("DNI Arrendatario:");
        jPanel2.add(lDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, 30));

        txtDniCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 160, 30));

        lIdVivienda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lIdVivienda.setText("Identificador Vivienda:");
        jPanel2.add(lIdVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 180, 30));

        txtIdVivienda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtIdVivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 160, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pagado:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 80, 30));

        cbPagado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        jPanel2.add(cbPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 160, 30));

        btnInsert.setText("INSERTAR");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, 20));

        btnRead.setText("LEER");
        jPanel2.add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 20));

        btnUpdate.setText("MODIFICAR");
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 120, 20));

        btnDelete.setText("BORRAR");
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 90, 20));

        btnBack.setText("VOLVER");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, 20));

        btnSearch.setText("BUSCAR");
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 90, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NÚMERO EXPEDIENTE", "FECHA ENTRADA", "FECHA SALIDA", "CLIENTE", "ID VIVIENDA", "PAGADO"
            }
        ));
        tabla.setEnabled(false);
        jScrollPane1.setViewportView(tabla);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Alquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Alquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Alquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Alquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnInsert;
    public javax.swing.JButton btnRead;
    public javax.swing.JButton btnSearch;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JComboBox<String> cbPagado;
    public com.toedter.calendar.JDateChooser fechaEntrada;
    public com.toedter.calendar.JDateChooser fechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDniCliente;
    private javax.swing.JLabel lFechaEntrada;
    private javax.swing.JLabel lFechaSalida;
    private javax.swing.JLabel lIdVivienda;
    private javax.swing.JLabel lNumExp;
    private javax.swing.JLabel lTitle;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtDniCliente;
    public javax.swing.JTextField txtIdVivienda;
    public javax.swing.JTextField txtNumExp;
    // End of variables declaration//GEN-END:variables
}
